if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_NANOTIME -DBIT64 -DHAVE_VPRINTF -DHAVE_BACKTRACE -DHAVE_SLASHPROC -DHAVE_COMM_F2C -DHAVE_TIMES -DHAVE_GETTIMEOFDAY")
endif()

set(NetCDF_C_PATH "$ENV{NETCDF_C_ROOT}")
set(NetCDF_Fortran_PATH "$ENV{NETCDF_FORTRAN_ROOT}")

# Add our cmake finder scripts
list (APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/cmake)

set(LDFLAGS "")
string(APPEND SLIBS " -lnetcdf -lnetcdff -llapack -lblas")
